name: 'Licensed CI'
description: 'Ensure cached github/licensed license data is valid and up to date'
inputs:
  command:
    description: 'Licensed command to run'
    required: false
    default: 'licensed'
  github_token:
    description: 'Access token to push license updates to GitHub'
    required: true
  config_file:
    description: 'Path to licensed configuration file'
    required: false
    default: '.licensed.yml'
  user_name:
    description: 'Name to use when pushing file changes'
    required: false
    default: 'licensed-ci'
  user_email:
    description: 'Email to use when pushing file changes'
    required: false
    default: 'licensed-ci@users.noreply.github.com'
  commit_message:
    description: 'Message to use when committing file changes'
    required: false
    default: 'Auto-update license files'
  pr_comment:
    description: '(Deprecated) Comment to add to a pull request, if one exists for the branch'
    required: false
  workflow:
    description: Which workflow to run when metadata is updated.  See README for more details.
    required: false
    default: push
branding:
  icon: check-circle
  color: green
runs:
  using: 'node12'
  main: 'lib/index.js'
