name: Verify cached license metadata

on:
  # run on pushes to main
  push:
    branches:
      - main
  # run on all pull request events
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # run on demand
  workflow_dispatch:

jobs:
  licensed:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    # setup node environment and packages
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - run: npm install --production --ignore-scripts

    # install licensed
    - uses: ruby/setup-ruby@2a18b06812b0e15bb916e1df298d3e740422c47e
      with:
        ruby-version: ruby
    - uses: github/setup-licensed@v1
      with:
        version: '4.x'

    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        config_file: .licensed.release.yml
        workflow: push_for_bots
        dependabot_skip: 'true'
