name: "Run licensed in test"
on: pull_request
permissions:
  contents: write
  pull-requests: write

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20.x ]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        cache: npm
        node-version: ${{ matrix.node }}

    - run: npm install --production --ignore-scripts

    # install licensed
    - uses: ruby/setup-ruby@bfefad842bb982ff05b233bcbc1571d97a87e69f
      with:
        ruby-version: ruby
    - uses: github/setup-licensed@v1
      with:
        version: '4.x'

    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: push
