name: "Run licensed in test"
on: pull_request

jobs:
  licensed_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14.x, 16.x, 18.x ]
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v3
      with:
        cache: npm
        node-version: ${{ matrix.node }}

    - run: npm install --production --ignore-scripts

    # install licensed
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
    - uses: github/setup-licensed@v1
      with:
        version: '4.x'

    - uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: push
